artifact_id := `sed -n 's/^module //p' go.mod`
version := `tr -d '[:space:]' < VERSION`
image := artifact_id + ":" + version

# List available recipes
default:
    @just --list

# Compile the application
compile:
    mkdir -p bin
    go build -ldflags "-X main.version={{version}}" -o bin/{{artifact_id}} .

# Run the application locally
run:
    go run -ldflags "-X main.version={{version}}" .

# Build the Docker image
docker-build:
    docker build -t {{image}} .

# Run the Docker container
docker-run:
    docker run --rm -p 8080:8080 {{image}}
