apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../apps/cash-manager-be/overlays/local
  - ../../apps/weight-record-be/overlays/local
  - ../../apps/news-collector-be/overlays/local
