apiVersion: v1
kind: ConfigMap
metadata:
  name: news-collector-be
  labels:
    app.kubernetes.io/name: news-collector-be
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: control-panel
data:
  PORT: "8080"
  LOG_LEVEL: debug
