apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: control-panel

resources:
  - ../../base

images:
  - name: cash-manager
    newName: cash-manager
    newTag: 0.0.1-SNAPSHOT

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
